GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAyMGQzZjBmMmZlMTE5OWZiOTg3NGQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2NzgyMDkyNDksImV4cCI6MTY3ODIxMjg0OX0.fpyXSHDXwJu4vTAOe6wzHi9TYqUBEaB06O-sRZb1nRs HTTP/1.1