DELETE http://localhost:5000/api/tasks/640227c15afa256f6b85dad5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAyMGQzZjBmMmZlMTE5OWZiOTg3NGQiLCJlbWFpbCI6InBvdHRlckBob2d3YXJ0cy5jb20iLCJpYXQiOjE2Nzg4OTY5MjUsImV4cCI6MTY3ODg5Njk4NX0.N5m7xyl3lj2Ia7YmP03tLEongeaA_DefkVFGD1wy6XE